name: Run

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to deb file"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Convert deb to IPA
        run: |
          git clone https://github.com/ToshioCP/Gtk4-tutorial.git
          cd Gtk4-tutorial
          apt install -y texlive-latex-extra
          apt install -y pandoc
          rake pdf
          
      - name: Upload IPA
        uses: actions/upload-artifact@v3.1.0
        with:
          name: App
          path: ${{ github.workspace }}/App.ipa
