name: Compile

on:
  push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Compile tutorial
        run: |
          git clone https://github.com/ToshioCP/Gtk4-tutorial.git
          cd Gtk4-tutorial
          sudo apt install -y texlive-latex-extra
          sudo apt install -y pandoc ruby-full rake
          rake html
          zip -r ../artfact.zip docs
          echo "FIRST"
          cd ..
          echo "SECOND"
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact.zip
